"""
backend/tools/volume.py

Volume Calculator tool for NoFishyBusiness.

Computes aquarium water volume (in US gallons) and the corresponding water
weight (in pounds) from tank dimensions given in inches.

The calculation itself is pure Python math — no LLM needed.
An optional LLM call adds a "pro_tip" about the practical implications of
the calculated weight (floor load, stand stability, etc.) using the
PromptFactory "volume" persona.

Formulas
--------
- volume_gallons = round((length * width * depth) / 231.0, 2)
  (231 cubic inches = 1 US gallon)
- weight_pounds  = round(volume_gallons * 8.34, 2)
  (fresh water weighs approximately 8.34 lb per US gallon)
"""

import json

import openai

from backend import logger
from backend.models import UserContext
from backend.prompt_factory import PromptFactory

# ---------------------------------------------------------------------------
# OpenAI client — lazy singleton
# ---------------------------------------------------------------------------

_client: openai.OpenAI | None = None


def _get_client() -> openai.OpenAI:
    """Return the shared OpenAI client, creating it on first use."""
    global _client
    if _client is None:
        _client = openai.OpenAI()
    return _client


def calculate_volume(length: float, width: float, depth: float) -> dict:
    """
    Calculate aquarium water volume and weight from tank dimensions.

    Also calls the LLM to generate a practical pro-tip about the weight
    (e.g. floor joist load limits, stand requirements). The pro-tip is
    generated by the PromptFactory "volume" persona — "The Practical Engineer."

    Args:
        length: Tank length in inches (must be positive).
        width:  Tank width in inches (must be positive).
        depth:  Water depth in inches (must be positive).

    Returns:
        A dict with keys:
          - ``volume_gallons`` (float): Water volume rounded to 2 decimal places.
          - ``weight_pounds``  (float): Water weight rounded to 2 decimal places.
          - ``pro_tip``        (str):   Practical advice about the weight (from LLM).
    """
    # ── Pure math — no LLM needed ─────────────────────────────────────────
    volume_gallons = round((length * width * depth) / 231.0, 2)
    weight_pounds  = round(volume_gallons * 8.34, 2)

    result = {
        "volume_gallons": volume_gallons,
        "weight_pounds":  weight_pounds,
        "pro_tip":        None,   # Filled in by LLM call below
    }

    # ── LLM pro-tip enrichment ────────────────────────────────────────────
    # The PromptFactory "volume" persona generates a practical tip about the
    # weight result. This is the only LLM call in the volume tool — the math
    # is always done first so the result is available even if the LLM fails.
    try:
        system_prompt = PromptFactory.get_prompt(
            feature_id="volume",
            context="",   # Volume tool doesn't use RAG
            user=UserContext.guest(),
        )

        response = _get_client().chat.completions.create(
            model="gpt-4o-mini",
            max_tokens=200,   # Pro-tip is short — cap tokens for cost efficiency
            messages=[
                {"role": "system", "content": system_prompt},
                {
                    "role": "user",
                    "content": (
                        f"Tank dimensions: {length}\" × {width}\" × {depth}\". "
                        f"Volume: {volume_gallons} gallons. "
                        f"Weight: {weight_pounds} lbs. "
                        "Provide a practical pro-tip about this weight."
                    ),
                },
            ],
        )

        # Log the LLM call
        usage = response.usage
        if usage:
            logger.log_llm_call(
                prompt_tokens=usage.prompt_tokens,
                completion_tokens=usage.completion_tokens,
                total_tokens=usage.total_tokens,
            )

        # Parse the pro_tip from the JSON response
        raw = response.choices[0].message.content or ""
        raw = raw.strip()
        if raw.startswith("```"):
            lines = raw.splitlines()
            lines = lines[1:] if lines[0].startswith("```") else lines
            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]
            raw = "\n".join(lines).strip()

        parsed = json.loads(raw)
        result["pro_tip"] = parsed.get("pro_tip")

    except (openai.OpenAIError, json.JSONDecodeError, Exception) as exc:
        # Pro-tip is optional — if the LLM call fails, return the math result
        # without it. Never let the enrichment layer break the core calculation.
        logger.log_error("VolumeTipError", str(exc))
        result["pro_tip"] = None

    return result
